### ISSUE TITLE
perhaps, occur memory leak

### ISSUE THREAD

**Issue by jongho123** [flow-er/homeflow#2]
[parseFlow() in flow.c 13-39](https://github.com/flow-er/homeflow/blob/master/src/home_device/types/flow.c#L13-L39)

``` C
struct flow *parseFlow(const char *path) {
    struct flow *flow = (struct flow *) malloc(sizeof(struct flow));
    ....
    flow->head = parseNode(root->children);
    ....
}
```

[parseNode() in flow.c 41-59](https://github.com/flow-er/homeflow/blob/master/src/home_device/types/flow.c#L41-L59)

``` C
struct node *parseNode(xmlNode *elem) {
    ....
    for (i = T_ACTION; i <= T_TRIGGER; i++) {
        if (!strcmp((const char *) elem->name, nTypeName[i])) {
            node = (struct node *) malloc(sizeof(struct node));
            node->child = node->next = NULL;
            ....
        }
    }

    if (elem->children) node->child = parseNode(elem->children);
    if (elem->next) node->next = parseNode(elem->next);

    return node;
}
```

Allocate dynamic memory by call parseFlow() in scheduler.c. but not deallocate following code in [scheduler.c 63-73](https://github.com/flow-er/homeflow/blob/master/src/home_device/types/scheduler.c#L63-L73)

``` C
curr->flow = parseFlow(full);
....
for (old = scheduler->head; old != NULL; old = old->next) {
    if (old->flow->id == id) {
        if(old->prev) old->prev->next = old->next;
        if(old->next) old->next->prev = old->prev;

        free(old);

        remove(origin);
        break;
    }
}
```

after free(), I think no way can refer to "old-> flow". Therefore will occur memory leak perhaps.
i think must be used 'freeFlow(old->flow)' before 'free(old)'.

**Comment by jigi-kim** [comment]
Agree with that.
